---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-demo
  namespace: microservices-demo
secrets:
- name: harbor-credentials
imagePullSecrets:
- name: harbor-credentials

---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: paymentservice
  namespace: microservices-demo
spec:
  tag:  harbor.vmw.binbytes.io/microservices-demo/paymentservice
  serviceAccount: microservices-demo
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/logankimmel/microservices-demo.git
      revision: tbs
    subPath: src/paymentservice
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: currencyservice
  namespace: microservices-demo
spec:
  tag:  harbor.vmw.binbytes.io/microservices-demo/currencyservice
  serviceAccount: microservices-demo
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/logankimmel/microservices-demo.git
      revision: tbs
    subPath: src/currencyservice

---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: frontend
  namespace: microservices-demo
spec:
  serviceAccount: microservices-demo
  tag:  harbor.vmw.binbytes.io/microservices-demo/frontend
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/logankimmel/microservices-demo.git
      revision: tbs
    subPath: src/frontend
  build:
    env:
      - name: BP_KEEP_FILES
        value: 'static/*:templates/*'
  
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: productcatalogservice
  namespace: microservices-demo
spec:
  serviceAccount: microservices-demo
  tag:  harbor.vmw.binbytes.io/microservices-demo/productcatalogservice
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/logankimmel/microservices-demo.git
      revision: tbs
    subPath: src/productcatalogservice
  build:
    env:
      - name: BP_KEEP_FILES
        value: 'products.json'
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: shippingservice
  namespace: microservices-demo
spec:
  serviceAccount: microservices-demo
  tag:  harbor.vmw.binbytes.io/microservices-demo/shippingservice
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/logankimmel/microservices-demo.git
      revision: tbs
    subPath: src/shippingservice
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: checkoutservice
  namespace: microservices-demo
spec:
  serviceAccount: microservices-demo
  tag:  harbor.vmw.binbytes.io/microservices-demo/checkoutservice
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/logankimmel/microservices-demo.git
      revision: tbs
    subPath: src/checkoutservice
---
# Creates Spring Pet Clinic image to be built
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: cartservice
  namespace: microservices-demo
spec:
  serviceAccount: microservices-demo
  tag:  harbor.vmw.binbytes.io/microservices-demo/cartservice
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/logankimmel/microservices-demo.git
      revision: tbs
    subPath: "src/cartservice/src"
  
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: emailservice
  namespace: microservices-demo
spec:
  serviceAccount: microservices-demo
  tag:  harbor.vmw.binbytes.io/microservices-demo/emailservice
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/logankimmel/microservices-demo.git
      revision: tbs
    subPath: "src/emailservice"

---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: recommendationservice
  namespace: microservices-demo
spec:
  serviceAccount: microservices-demo
  tag:  harbor.vmw.binbytes.io/microservices-demo/recommendationservice
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/logankimmel/microservices-demo.git
      revision: tbs
    subPath: "src/recommendationservice"

---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: loadgenerator
  namespace: microservices-demo
spec:
  serviceAccount: microservices-demo
  tag:  harbor.vmw.binbytes.io/microservices-demo/loadgenerator
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/logankimmel/microservices-demo.git
      revision: tbs
    subPath: "src/loadgenerator"

---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: adservice
  namespace: microservices-demo
spec:
  serviceAccount: microservices-demo
  tag:  harbor.vmw.binbytes.io/microservices-demo/adservice
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/logankimmel/microservices-demo.git
      revision: tbs
    subPath: "src/adservice"